import { Product } from './types';

// Sample structural data for template/demo purposes.
// Replace with verified specifications and photography before launch.
export const products: Product[] = [
  {
    slug: 'engraved-beach-compass-decor',
    sku: 'MWC-BCH-101',
    name: 'Engraved Wooden Beach Compass Wall Decor',
    categorySlug: 'beach-theme-decor',
    shortDescription: 'Hand-carved nautical compass with brass-tone inlay, ready for wall or shelf display.',
    description:
      'A statement coastal piece for resort lobbies, beach villas, and souvenir shelves. Each compass is hand-carved from solid sheesham wood, inlaid with a brass-tone metal dial, and finished with a hand-antiqued matte lacquer for a weathered, premium look. Popular as a standalone wall hanging or paired with our lighthouse and anchor pieces for a coordinated coastal display.',
    images: ['beach', 'beach', 'beach'],
    material: 'Solid sheesham wood (Indian rosewood) with brass-tone metal inlay',
    weightRange: '350 g – 450 g',
    dimensions: 'Ø 20 cm x 3 cm (custom sizes available: 15 cm / 25 cm / 30 cm)',
    finish: 'Hand-antiqued matte lacquer',
    moq: '500 pieces per design',
    leadTime: '30–35 days after sample approval',
    packagingType: 'Individual kraft gift box, 12 pcs per export carton (5-ply)',
    customizable: true,
    isBestseller: true,
    tags: ['nautical', 'wall decor', 'resort'],
  },
  {
    slug: 'driftwood-style-anchor-sculpture',
    sku: 'MWC-BCH-102',
    name: 'Driftwood-Style Wooden Anchor Sculpture',
    categorySlug: 'beach-theme-decor',
    shortDescription: 'Freestanding anchor sculpture with a distressed driftwood finish for coastal retail displays.',
    description:
      'A best-selling silhouette for beach gift shops and coastal home stores. Carved from mango wood and hand-finished to a distressed, sun-bleached driftwood effect, this anchor sculpture stands freely on a shelf, counter, or console table. Available in three sizes to suit both retail impulse-buy shelving and premium display units.',
    images: ['beach', 'beach'],
    material: 'Solid mango wood',
    weightRange: '600 g – 1.2 kg (size-dependent)',
    dimensions: '25 cm / 35 cm / 45 cm height options',
    finish: 'Distressed whitewash, driftwood effect',
    moq: '500 pieces (mixed sizes accepted)',
    leadTime: '30–35 days after sample approval',
    packagingType: 'Bubble-wrapped, honeycomb carton with corner protection',
    customizable: true,
    tags: ['nautical', 'sculpture', 'shelf decor'],
  },
  {
    slug: 'nautical-rope-lighthouse-showpiece',
    sku: 'MWC-BCH-103',
    name: 'Nautical Rope & Wood Lighthouse Showpiece',
    categorySlug: 'beach-theme-decor',
    shortDescription: 'Turned-wood lighthouse showpiece wrapped in natural jute rope with a hand-painted lantern top.',
    description:
      'A high-visibility centrepiece for coastal-themed retail counters. The tapered lighthouse body is wood-turned, wrapped in natural jute rope banding, and topped with a hand-painted lantern accent. Ships flat-packed with the base and body pre-fitted for fast in-store assembly.',
    images: ['beach', 'beach'],
    material: 'Solid pinewood with natural jute rope and hand-painted accents',
    weightRange: '400 g – 550 g',
    dimensions: '30 cm height x 8 cm base diameter',
    finish: 'Natural wood stain with painted lantern detail',
    moq: '500 pieces',
    leadTime: '30–35 days after sample approval',
    packagingType: 'Individual box, 10 pcs per export carton',
    customizable: false,
    tags: ['nautical', 'showpiece', 'counter display'],
  },
  {
    slug: 'wooden-fridge-magnet-souvenir-set',
    sku: 'MWC-SOU-201',
    name: 'Destination Wooden Fridge Magnet Set',
    categorySlug: 'wooden-souvenirs',
    shortDescription: 'Laser-engraved wooden fridge magnets customised with destination names, skylines, or landmarks.',
    description:
      'Our highest-velocity SKU for tourist retail and airport gift counters. Each magnet is laser-engraved to order with your destination name, landmark outline, or custom artwork, and fitted with a high-strength ceramic magnet. Sold as single designs or curated destination sets of 6–12 pieces.',
    images: ['souvenir', 'souvenir', 'souvenir'],
    material: 'Birch plywood with ceramic magnet backing',
    weightRange: '15 g – 25 g per piece',
    dimensions: '6 cm x 6 cm (custom shapes available)',
    finish: 'Natural wood with laser-engraved detail',
    moq: '1,000 pieces per design (mixed-design cartons available)',
    leadTime: '20–25 days after sample approval',
    packagingType: 'Poly bag with header card, 100 pcs per inner box',
    customizable: true,
    isBestseller: true,
    tags: ['souvenir', 'engraved', 'retail counter'],
  },
  {
    slug: 'engraved-keychain-destination-souvenir',
    sku: 'MWC-SOU-202',
    name: 'Engraved Wooden Keychain Souvenir',
    categorySlug: 'wooden-souvenirs',
    shortDescription: 'Compact laser-engraved keychains for destination branding and hotel gift shop counters.',
    description:
      'A low-cost, high-margin impulse item for hotel front desks, souvenir kiosks, and duty-free counters. Each keychain is laser-cut and engraved from sustainably sourced plywood, with a nickel-plated ring and clasp. Artwork, text, and destination branding are fully customisable per order.',
    images: ['souvenir', 'souvenir'],
    material: 'Engineered plywood with nickel-plated hardware',
    weightRange: '10 g – 18 g per piece',
    dimensions: '4 cm x 8 cm average',
    finish: 'Natural wood with laser-engraved detail',
    moq: '1,000 pieces per design',
    leadTime: '20–25 days after sample approval',
    packagingType: 'Poly bag with header card, 200 pcs per inner box',
    customizable: true,
    tags: ['souvenir', 'engraved', 'keychain'],
  },
  {
    slug: 'wooden-coaster-set-with-stand',
    sku: 'MWC-TBL-301',
    name: 'Wooden Coaster Set with Display Stand',
    categorySlug: 'table-decor',
    shortDescription: 'Set of 6 mango wood coasters with a matching countertop display stand.',
    description:
      'A hospitality and home-store staple. Each set includes six food-safe finished mango wood coasters and a matching wooden display stand for retail shelving or hotel room presentation. Surface can be laser-engraved with a logo, monogram, or destination motif for private label programmes.',
    images: ['table', 'table', 'table'],
    material: 'Solid mango wood, food-safe lacquer finish',
    weightRange: '450 g – 600 g per set of 6',
    dimensions: 'Coaster: 10 cm x 10 cm; Stand: 11 cm x 11 cm x 9 cm',
    finish: 'Food-safe matte lacquer',
    moq: '500 sets',
    leadTime: '30–35 days after sample approval',
    packagingType: 'Rigid gift box per set, 10 sets per export carton',
    customizable: true,
    tags: ['tableware', 'hospitality', 'private label'],
  },
  {
    slug: 'mango-wood-serving-tray',
    sku: 'MWC-TBL-302',
    name: 'Mango Wood Serving Tray with Handles',
    categorySlug: 'table-decor',
    shortDescription: 'Solid mango wood serving tray with brass-tone cutout handles for hospitality and retail.',
    description:
      'A versatile serving and display tray sourced from solid mango wood offcuts, reducing timber wastage while delivering a premium natural grain finish. Brass-tone cutout handles provide secure carrying for hospitality use, while the flat profile suits retail shelf merchandising.',
    images: ['table', 'table'],
    material: 'Solid mango wood with brass-tone metal handles',
    weightRange: '700 g – 950 g',
    dimensions: '35 cm x 22 cm x 5 cm',
    finish: 'Natural food-safe oil finish',
    moq: '500 pieces',
    leadTime: '30–35 days after sample approval',
    packagingType: 'Kraft sleeve, 20 pcs per export carton',
    customizable: true,
    tags: ['serving tray', 'hospitality', 'home decor'],
  },
  {
    slug: 'handcarved-wall-mirror-frame',
    sku: 'MWC-HOM-401',
    name: 'Hand-Carved Wooden Wall Mirror Frame',
    categorySlug: 'home-decor',
    shortDescription: 'Round wall mirror in a hand-carved sheesham wood frame with a coastal-inspired motif.',
    description:
      'An anchor SKU for premium home decor assortments. The mirror frame is hand-carved from solid sheesham wood in a coastal wave motif, fitted with a 5 mm shatter-resistant mirror, and wall-mounted with a concealed hanging bracket. Frame carving pattern can be adapted for private-label collections.',
    images: ['home', 'home', 'home'],
    material: 'Solid sheesham wood frame, 5 mm mirror glass',
    weightRange: '1.8 kg – 2.4 kg',
    dimensions: 'Ø 45 cm (custom sizes: 35 cm / 55 cm)',
    finish: 'Hand-carved, natural wood polish',
    moq: '500 pieces',
    leadTime: '35–40 days after sample approval',
    packagingType: 'Foam-cornered rigid carton with mirror-safe wrap',
    customizable: true,
    isBestseller: true,
    tags: ['wall decor', 'mirror', 'premium'],
  },
  {
    slug: 'wooden-tealight-holder-set',
    sku: 'MWC-HOM-402',
    name: 'Carved Wooden Tealight Holder Set',
    categorySlug: 'home-decor',
    shortDescription: 'Set of 3 hand-carved tealight holders in graduated sizes for ambient home styling.',
    description:
      'A fast-moving gifting and home-styling SKU. Each set includes three graduated tealight holders hand-carved from acacia wood with a lattice cutout pattern that casts warm ambient light. Sold individually or bundled as gift sets with tealight candles (candles supplied by buyer or on request).',
    images: ['home', 'home'],
    material: 'Solid acacia wood',
    weightRange: '250 g – 400 g per set of 3',
    dimensions: '8 cm / 10 cm / 12 cm height (graduated set)',
    finish: 'Natural wood polish',
    moq: '500 sets',
    leadTime: '30–35 days after sample approval',
    packagingType: 'Printed gift box per set, 15 sets per export carton',
    customizable: true,
    tags: ['tealight', 'ambient lighting', 'gifting'],
  },
  {
    slug: 'couple-initial-photo-frame',
    sku: 'MWC-CPL-501',
    name: 'Couple Initial Engraved Wooden Photo Frame',
    categorySlug: 'couple-honeymoon-souvenirs',
    shortDescription: 'Personalised wooden photo frame engraved with couple initials or destination and date.',
    description:
      'Designed for the honeymoon and destination-wedding gifting market. Each frame is laser-engraved with couple initials, wedding date, or destination name, and finished in a warm walnut-tone stain. Popular as a resort welcome gift, honeymoon package add-on, or retail counter personalisation offer.',
    images: ['couple', 'couple', 'couple'],
    material: 'Solid pinewood with walnut-tone stain',
    weightRange: '300 g – 380 g',
    dimensions: '20 cm x 15 cm (fits standard 6x4" / 8x6" prints)',
    finish: 'Walnut-tone stain, laser-engraved detail',
    moq: '500 pieces',
    leadTime: '25–30 days after sample approval',
    packagingType: 'Individual gift box, 20 pcs per export carton',
    customizable: true,
    tags: ['honeymoon', 'personalised', 'photo frame'],
  },
  {
    slug: 'honeymoon-memory-box',
    sku: 'MWC-CPL-502',
    name: 'Engraved Wooden Honeymoon Memory Box',
    categorySlug: 'couple-honeymoon-souvenirs',
    shortDescription: 'Keepsake wooden memory box for honeymoon mementos, engraved with names or resort branding.',
    description:
      'A premium keepsake for couples and a strong co-branding opportunity for resorts. This lined wooden memory box stores photographs, tickets, and small mementos, with the lid available for engraving with couple names, wedding dates, or resort/hotel branding as a welcome amenity.',
    images: ['couple', 'couple'],
    material: 'Solid mango wood, fabric-lined interior',
    weightRange: '550 g – 700 g',
    dimensions: '20 cm x 15 cm x 8 cm',
    finish: 'Natural wood polish with engraved lid',
    moq: '500 pieces',
    leadTime: '30–35 days after sample approval',
    packagingType: 'Kraft sleeve box, 12 pcs per export carton',
    customizable: true,
    tags: ['honeymoon', 'keepsake box', 'resort amenity'],
  },
  {
    slug: 'custom-logo-engraved-corporate-gift-set',
    sku: 'MWC-CUS-601',
    name: 'Custom Logo-Engraved Corporate Gift Set',
    categorySlug: 'custom-wooden-gifts',
    shortDescription: 'Fully customisable wooden gift set built to your brand logo, packaging, and specification.',
    description:
      'A build-to-brief programme for corporate gifting agencies, resort chains, and private-label distributors. Combine any of our wood types, finishes, and hardware with your logo engraving, custom packaging, and insert cards. Final specification, pricing, and MOQ are confirmed after a design consultation.',
    images: ['gift', 'gift', 'gift'],
    material: 'Buyer-specified (sheesham / mango / acacia / pinewood)',
    weightRange: 'Depends on final specification',
    dimensions: 'Depends on final specification',
    finish: 'Buyer-specified',
    moq: '500 pieces per SKU (private label programmes discussed individually)',
    leadTime: 'Confirmed after design and sample approval',
    packagingType: 'Custom-branded packaging designed to specification',
    customizable: true,
    tags: ['corporate gifting', 'private label', 'custom'],
  },
  {
    slug: 'palm-wave-honeymoon-plaque',
    sku: 'MWC-CPL-503',
    name: 'Engraved Palm & Wave Honeymoon Plaque',
    categorySlug: 'couple-honeymoon-souvenirs',
    shortDescription: 'Hand-carved palm tree and wave tabletop plaque, personalised with names, a date, or "Honeymoon" script.',
    description:
      'Our most-requested honeymoon keepsake: a hand-carved palm tree and cresting wave silhouette with a seated couple figure, mounted on a solid wood base engraved with a name, date, or destination. A strong seller for resort gift counters and destination-wedding retailers across coastal markets.',
    images: [
      '/photos/products/honeymoon-palm-wave-plaque-1.jpg',
      '/photos/products/honeymoon-palm-wave-plaque-2.jpg',
      '/photos/products/honeymoon-palm-wave-plaque-3.jpg',
      '/photos/products/honeymoon-palm-wave-plaque-4.jpg',
      '/photos/products/honeymoon-palm-wave-plaque-5.jpg',
    ],
    material: 'Solid beech wood, hand-carved and engraved',
    weightRange: '180 g – 260 g',
    dimensions: '18 cm – 20 cm width (7–8 inch), custom sizes available',
    finish: 'Natural wood polish with hand-engraved text',
    moq: '500 pieces per design',
    leadTime: '25–30 days after sample approval',
    packagingType: 'Individual kraft box, 20 pcs per export carton',
    customizable: true,
    isBestseller: true,
    tags: ['honeymoon', 'palm tree', 'engraved', 'bestseller'],
  },
  {
    slug: 'sea-turtle-couple-keepsake',
    sku: 'MWC-CPL-504',
    name: 'Sea Turtle Companion Wooden Keepsake',
    categorySlug: 'couple-honeymoon-souvenirs',
    shortDescription: 'Carved couple figures bound with natural jute rope, riding a hand-carved sea turtle base.',
    description:
      'A distinctive alternative to our standard honeymoon plaque — two rope-bound wooden figures carved standing atop a detailed sea turtle sculpture, symbolising togetherness and safe travels. Popular as a premium add-on gift alongside our palm & wave collection.',
    images: ['/photos/products/sea-turtle-couple-keepsake-1.jpg'],
    material: 'Solid beech wood with natural jute rope binding',
    weightRange: '150 g – 220 g',
    dimensions: 'Approx. 15 cm height',
    finish: 'Natural wood polish',
    moq: '500 pieces',
    leadTime: '25–30 days after sample approval',
    packagingType: 'Individual kraft box, 20 pcs per export carton',
    customizable: true,
    tags: ['honeymoon', 'turtle', 'keepsake'],
  },
  {
    slug: 'custom-destination-wave-plaque',
    sku: 'MWC-SOU-203',
    name: 'Custom Destination Name Wave Plaque',
    categorySlug: 'wooden-souvenirs',
    shortDescription: 'Palm, wave, and sailboat plaque hand-engraved with any destination name for local souvenir retail.',
    description:
      'Built for tourist-board and beach-resort retail counters: a palm tree, cresting wave, and sailboat silhouette on a solid wood base, engraved to order with any destination name (e.g. "Mauritius"). Sold as single-destination runs or mixed-destination assortments for multi-location retailers.',
    images: ['/photos/products/custom-destination-wave-plaque-1.jpg'],
    material: 'Solid beech wood, hand-engraved',
    weightRange: '200 g – 280 g',
    dimensions: '18 cm – 22 cm width',
    finish: 'Natural wood polish with engraved detail',
    moq: '500 pieces per destination name',
    leadTime: '20–25 days after sample approval',
    packagingType: 'Individual kraft box, 20 pcs per export carton',
    customizable: true,
    isBestseller: true,
    tags: ['destination', 'customisable', 'souvenir'],
  },
  {
    slug: 'palm-wave-coastal-accent',
    sku: 'MWC-BCH-104',
    name: 'Palm Tree & Wave Coastal Accent Décor',
    categorySlug: 'beach-theme-decor',
    shortDescription: 'Minimalist palm tree and wave silhouette in solid wood — an unpersonalised coastal shelf accent.',
    description:
      'A clean, non-personalised companion piece to our engraved plaque range. The same hand-carved palm tree and cresting wave silhouette, without text, for buyers who want a versatile coastal accent for shelving, console tables, or bundled retail displays.',
    images: ['/photos/products/palm-wave-coastal-accent-1.jpg', '/photos/products/palm-wave-coastal-accent-2.jpg'],
    material: 'Solid beech wood',
    weightRange: '180 g – 250 g',
    dimensions: '15 cm – 18 cm width',
    finish: 'Natural wood polish',
    moq: '500 pieces',
    leadTime: '30–35 days after sample approval',
    packagingType: 'Individual kraft box, 20 pcs per export carton',
    customizable: false,
    tags: ['beach decor', 'palm tree', 'coastal accent'],
  },
  {
    slug: 'rustic-longhorn-wall-decor',
    sku: 'MWC-HOM-403',
    name: 'Rustic Wooden Longhorn Wall Décor',
    categorySlug: 'home-decor',
    shortDescription: 'Statement hand-finished wooden longhorn wall mount for premium home and lifestyle retail.',
    description:
      'A large-format statement wall piece for premium home decor assortments and feature-wall retail displays. Hand-finished in a rich rustic lacquer with a solid wood mounting plaque and concealed wall-mount hardware for easy installation.',
    images: [
      '/photos/products/rustic-longhorn-wall-decor-1.jpg',
      '/photos/products/rustic-longhorn-wall-decor-2.jpg',
      '/photos/products/rustic-longhorn-wall-decor-3.jpg',
    ],
    material: 'Solid wood, hand-finished rustic lacquer',
    weightRange: '900 g – 1.3 kg',
    dimensions: 'L 30.5 in x H 10.5 in x D 2 in (77 cm x 27 cm x 5 cm)',
    finish: 'Hand-finished rustic lacquer',
    moq: '500 pieces',
    leadTime: '35–40 days after sample approval',
    packagingType: 'Foam-cornered rigid carton, wall-mount hardware included',
    customizable: false,
    isBestseller: true,
    tags: ['wall decor', 'rustic', 'longhorn', 'statement piece'],
  },
  {
    slug: 'wooden-school-of-fish-sculpture',
    sku: 'MWC-HOM-404',
    name: 'Wooden School of Fish Stand Sculpture',
    categorySlug: 'home-decor',
    shortDescription: 'Four hand-carved wooden fish suspended at graduated heights on a solid wood display base.',
    description:
      'A playful, contemporary tabletop sculpture for coastal-styled home decor assortments. Four individually carved wooden fish are mounted at graduated heights on slim metal rods over a solid wood base, catching the light as a shelf or console centrepiece.',
    images: [
      '/photos/products/wooden-school-of-fish-sculpture-1.jpg',
      '/photos/products/wooden-school-of-fish-sculpture-2.jpg',
    ],
    material: 'Solid wood with metal display rods, wood base',
    weightRange: '250 g – 350 g',
    dimensions: 'L 8 in x H 6.5 in x W 2 in (20 cm x 16.5 cm x 5 cm)',
    finish: 'Natural wood polish',
    moq: '500 pieces',
    leadTime: '30–35 days after sample approval',
    packagingType: 'Individual box, 15 pcs per export carton',
    customizable: false,
    tags: ['home decor', 'fish sculpture', 'tabletop'],
  },
];

export function getProductBySlug(slug: string) {
  return products.find((p) => p.slug === slug);
}

export function getProductsByCategory(categorySlug: string) {
  return products.filter((p) => p.categorySlug === categorySlug);
}

export function getRelatedProducts(product: Product, limit = 4) {
  return products
    .filter((p) => p.categorySlug === product.categorySlug && p.slug !== product.slug)
    .slice(0, limit);
}
